// Generated by scripts/gen-browser.ts. Set parameters first, e.g.:
// :param deal => "nimbus"
// :param iteration => 1
// Turn OFF "Connect result nodes" in Browser settings for the scene queries.

// Scene 1: Knowledge (patterns in play, their tasks, related patterns)
// Scene 1, Knowledge (T4.2 addendum §4.1): patterns in play this iteration, related patterns, and tasks.
// Groups in priority order: selected patterns, other candidates, related patterns, tasks. Always one row.
OPTIONAL MATCH (:Selection {deal_code: $deal, iteration: $iteration})-[:SELECTS]->(sp:Pattern)
WITH collect(DISTINCT sp) AS selected
OPTIONAL MATCH (:Candidate {deal_code: $deal, iteration: $iteration})-[:OF]->(cp:Pattern)
WITH selected, [p IN collect(DISTINCT cp) WHERE NOT p IN selected] AS candidates
WITH selected, candidates, selected + candidates AS pats
OPTIONAL MATCH (p:Pattern)-[:REQUIRES|CONFLICTS|AUGMENTS]-(q:Pattern)
WHERE p IN pats AND NOT q IN pats
WITH selected, candidates, pats, collect(DISTINCT q) AS related
OPTIONAL MATCH (p:Pattern)-[:HAS_TASK]->(t:Task)
WHERE p IN pats
WITH selected, candidates, related, collect(DISTINCT t) AS tasks
RETURN [selected, candidates, related, tasks] AS groups

// Scene 2: Plan (the iteration, its plan nodes, findings, patterns)
// Scene 2, Plan (T4.2 addendum §4.1): the iteration's plan nodes, the findings they were framed from, and
// the patterns they select. Groups in priority order. Always one row.
OPTIONAL MATCH (i:Iteration {deal_code: $deal, n: $iteration})
OPTIONAL MATCH (x)-[:IN_ITERATION]->(i)
WITH i, collect(DISTINCT x) AS planNodes
OPTIONAL MATCH (fu:FramedUseCase)-[:FRAMED_FROM]->(f:Finding)
WHERE fu IN planNodes
WITH i, planNodes, collect(DISTINCT f) AS findings
OPTIONAL MATCH (s:Selection)-[:SELECTS]->(p:Pattern)
WHERE s IN planNodes
WITH i, planNodes, findings, collect(DISTINCT p) AS patterns
OPTIONAL MATCH (cd:CapabilityDecision {deal_code: $deal, iteration: $iteration})
WITH i, planNodes, findings, patterns, collect(DISTINCT cd) AS decisions
RETURN [
  CASE WHEN i IS NULL THEN [] ELSE [i] END,
  [n IN planNodes WHERE n:Selection],
  [n IN planNodes WHERE n:FramedUseCase],
  [n IN planNodes WHERE n:PlanTask],
  findings,
  patterns,
  [n IN planNodes WHERE n:Candidate],
  decisions
] AS groups

// Scene 3: Decisions (gates, feedback, overrides, ontology terms)
// Scene 3, Decisions (T4.2 addendum §4.1): gate decisions, feedback, overrides, and ontology terms, plus
// what they point at. Groups in priority order. Always one row.
OPTIONAL MATCH (d)
WHERE (d:GateDecision OR d:Feedback OR d:Override) AND d.deal_code = $deal
WITH collect(d) AS decisions
OPTIONAL MATCH (t:OntologyTerm)
WHERE t.scope IN ['global', $deal] AND t.status IN ['proposed', 'active']
WITH decisions, collect(t) AS terms
WITH decisions, terms, decisions + terms AS anchors
OPTIONAL MATCH (a)-[:DECIDED_ON|ON|CONSTRAINS|RESOLVED_BY|MOTIVATED_BY]->(target)
WHERE a IN anchors
WITH decisions, terms, collect(DISTINCT target) AS targets
RETURN [decisions, terms, targets] AS groups

// Iteration diff (needs iteration >= 2)
// iteration_diff (DESIGN §5.3): what changed in iteration $iteration against the one before, per use case,
// with the text of every Feedback the new selection resolved (RESOLVED_BY). No rows when nothing changed.
CALL () {
  OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
  RETURN collect(s) AS now
}
CALL () {
  OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration - 1})
  RETURN collect(s) AS before
}
WITH now, before, [s IN now | s.uc] + [s IN before WHERE NOT s.uc IN [x IN now | x.uc] | s.uc] AS ucs
UNWIND ucs AS uc
WITH uc, head([s IN now WHERE s.uc = uc]) AS a, head([s IN before WHERE s.uc = uc]) AS b
WITH uc, a, b,
     CASE WHEN b IS NULL THEN 'added' WHEN a IS NULL THEN 'removed' WHEN a.pattern <> b.pattern THEN 'changed' END AS change
WHERE change IS NOT NULL
CALL (a) {
  OPTIONAL MATCH (f:Feedback)-[:RESOLVED_BY]->(a)
  WITH f ORDER BY f.id
  RETURN collect(f.text) AS feedback
}
RETURN uc, change, b.pattern AS before, a.pattern AS after, feedback
ORDER BY uc

// Resource load by skill and wave (after scheduling)
// Resource load (DESIGN §5.2 step 5): sum(weeks_e) per skill and wave for one iteration's scheduled plan.
MATCH (pt:PlanTask {deal_code: $deal, iteration: $iteration})
WHERE pt.wave IS NOT NULL
RETURN pt.skill AS skill, pt.wave AS wave, sum(pt.weeks_e) AS weeks, count(pt) AS tasks
ORDER BY wave, skill

// BB1 buy vs build
// BB1 buy vs build (DESIGN §5.3, §2.6): one row per capability type the deal has a capability finding for
// (classified as capability, so weak evidence is excluded). integrate_effort = sum of weeks_e of the
// PlanTasks of every Selection framed from those findings in this iteration (null when none is selected);
// build_effort = the type's BuildOption; coverage = the acquirer's best PROVIDES coverage (0 if none).
MATCH (:Deal {code: $deal})-[:HAS_FINDING]->(f:Finding)-[:IS_A]->(c:CapabilityType)
WHERE coalesce(f.classified_as, f.kind) = 'capability'
WITH c, collect(DISTINCT f) AS findings
CALL (findings) {
  UNWIND findings AS f
  OPTIONAL MATCH (f)<-[:FRAMED_FROM]-(:FramedUseCase {deal_code: $deal, iteration: $iteration})
                 <-[:FOR]-(:Selection {deal_code: $deal, iteration: $iteration})-[:HAS_TASK]->(pt:PlanTask)
  WITH DISTINCT pt
  RETURN CASE WHEN count(pt) = 0 THEN null ELSE sum(pt.weeks_e) END AS integrate_effort
}
CALL (c) {
  OPTIONAL MATCH (b:BuildOption)-[:DELIVERS]->(c)
  RETURN min(b.weeks_e) AS build_effort
}
CALL (c) {
  OPTIONAL MATCH (:PlatformCapability)-[p:PROVIDES]->(c)
  RETURN coalesce(max(p.coverage), 0.0) AS coverage
}
RETURN c.id AS capability_id, [f IN findings | f.id] AS finding_ids, integrate_effort, build_effort, coverage
ORDER BY capability_id

// Validator v1-prerequisite-closure
// V1 prerequisite closure (DESIGN §5.1, constraint): every pattern a selected pattern REQUIRES
// (up to 5 hops) is selected too. Witness: the REQUIRES path from the selected to the missing pattern.
// The skill derives (adds) the missing prerequisite.
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
OPTIONAL MATCH (s)-[:SELECTS]->(p:Pattern)
WITH count(s) AS examined, collect(DISTINCT p) AS selected
CALL (selected) {
  UNWIND selected AS p
  MATCH path = (p)-[:REQUIRES*1..5]->(missing:Pattern)
  WHERE NOT missing IN selected
  WITH p, missing, path
  ORDER BY p.id, missing.id, length(path)
  WITH p, missing, head(collect(path)) AS path
  RETURN collect({
    witness: [n IN nodes(path) | n.id],
    witness_eids: [n IN nodes(path) | elementId(n)],
    detail: p.id + ' requires ' + missing.id + ', which is not selected'
  }) AS violations
}
RETURN 'V1' AS check, examined, violations,
       CASE WHEN examined = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v2-conflicting-selections
// V2 conflicting selections (DESIGN §5.1, constraint): no two selected patterns CONFLICT (either direction).
// Witness: the two patterns. The skill repairs by switching one use case to its stored near-miss.
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
WITH collect(s) AS selections
CALL (selections) {
  UNWIND selections AS a
  UNWIND selections AS b
  MATCH (a)-[:SELECTS]->(pa:Pattern)-[:CONFLICTS]-(pb:Pattern)<-[:SELECTS]-(b)
  WHERE pa.id < pb.id
  WITH DISTINCT a, b, pa, pb
  ORDER BY pa.id, pb.id, a.uc, b.uc
  RETURN collect({
    witness: [pa.id, pb.id],
    witness_eids: [elementId(pa), elementId(pb)],
    detail: a.uc + ' selects ' + pa.id + ', which CONFLICTS with ' + pb.id + ' selected for ' + b.uc
  }) AS violations
}
RETURN 'V2' AS check, size(selections) AS examined, violations,
       CASE WHEN size(selections) = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v3-task-cycle
// V3 task cycle (DESIGN §5.1, structural): no PlanTask depends on itself through DEPENDS_ON (up to 10 hops).
// Witness: the cycle in DEPENDS_ON order, starting from its smallest id, closed (as the engine's CycleError).
// Only simple cycles count: no task appears twice before the end. Cycles longer than 10 hops are left to
// the scheduler, which refuses any cycle. Scheduling must not run while V3 fails.
OPTIONAL MATCH (t:PlanTask {deal_code: $deal, iteration: $iteration})
WITH collect(t) AS tasks
CALL (tasks) {
  UNWIND tasks AS t
  MATCH path = (t)-[:DEPENDS_ON*1..10]->(t)
  WHERE all(n IN nodes(path) WHERE n:PlanTask AND n.deal_code = $deal AND n.iteration = $iteration AND t.id <= n.id)
    AND size(reduce(seen = [], n IN tail(nodes(path)) | CASE WHEN n IN seen THEN seen ELSE seen + n END)) = length(path)
  WITH DISTINCT [n IN nodes(path) | n.id] AS witness, [n IN nodes(path) | elementId(n)] AS witness_eids
  ORDER BY reduce(k = '', id IN witness | k + id + '>')
  RETURN collect({
    witness: witness,
    witness_eids: witness_eids,
    detail: 'PlanTasks depend on each other in a cycle: ' + reduce(k = head(witness), id IN tail(witness) | k + ' -> ' + id)
  }) AS violations
}
RETURN 'V3' AS check, size(tasks) AS examined, violations,
       CASE WHEN size(tasks) = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v4-uncovered-critical-gap
// V4 uncovered critical gap (DESIGN §5.1, coverage): every critical gap finding of the deal is covered in
// this iteration by exact provenance: Finding <-FRAMED_FROM- FramedUseCase <-FOR- Selection.
// No track or use-case fallback (gotcha 07b). Examined: the iteration's Selections (the plan under check),
// so an empty plan is "nothing checked" and a plan for a deal without critical gaps passes.
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
WITH count(s) AS examined
CALL () {
  MATCH (:Deal {code: $deal})-[:HAS_FINDING]->(f:Finding)
  WHERE coalesce(f.classified_as, f.kind) = 'gap' AND f.severity = 'critical'
    AND NOT EXISTS {
      MATCH (f)<-[:FRAMED_FROM]-(:FramedUseCase {deal_code: $deal, iteration: $iteration})<-[:FOR]-(:Selection {deal_code: $deal, iteration: $iteration})
    }
  WITH f ORDER BY f.id
  RETURN collect({
    witness: [f.id],
    witness_eids: [elementId(f)],
    detail: 'critical gap ' + f.id + ' is not framed into any selected use case'
  }) AS violations
}
RETURN 'V4' AS check, examined, violations,
       CASE WHEN examined = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v5-excluded-pattern
// V5 excluded pattern (DESIGN §5.1, coverage): no Selection selects a pattern that an active
// exclude_pattern Override of this deal names. Witness: the pattern and the Override.
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
WITH collect(s) AS selections
CALL (selections) {
  UNWIND selections AS s
  MATCH (s)-[:SELECTS]->(p:Pattern)
  MATCH (o:Override {deal_code: $deal, kind: 'exclude_pattern', subject: p.id})
  WHERE o.active = true
  WITH s, p, o ORDER BY s.uc, o.id
  RETURN collect({
    witness: [p.id, o.id],
    witness_eids: [elementId(p), elementId(o)],
    detail: s.uc + ' selects ' + p.id + ', which ' + o.id + ' excludes'
  }) AS violations
}
RETURN 'V5' AS check, size(selections) AS examined, violations,
       CASE WHEN size(selections) = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v6-audit-chain
// V6 audit chain (DESIGN §5.1, audit): every Selection has a fit_score and a SELECTS edge, and every
// FramedUseCase a non-empty framing_rationale. Witness: the node's id (a Selection is identified by its uc).
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
WITH collect(s) AS selections
OPTIONAL MATCH (fu:FramedUseCase {deal_code: $deal, iteration: $iteration})
WITH selections, collect(fu) AS framings
CALL (selections, framings) {
  UNWIND selections + framings AS n
  WITH n
  WITH n, CASE
    WHEN n:Selection AND n.fit_score IS NULL THEN 'Selection ' + n.uc + ' has no fit_score'
    WHEN n:Selection AND NOT EXISTS { (n)-[:SELECTS]->(:Pattern) } THEN 'Selection ' + n.uc + ' selects no pattern'
    WHEN n:FramedUseCase AND trim(coalesce(n.framing_rationale, '')) = '' THEN 'FramedUseCase ' + n.id + ' has no framing_rationale'
  END AS problem
  WHERE problem IS NOT NULL
  WITH n, problem ORDER BY labels(n)[0], coalesce(n.uc, n.id)
  RETURN collect({witness: [coalesce(n.uc, n.id)], witness_eids: [elementId(n)], detail: problem}) AS violations
}
RETURN 'V6' AS check, size(selections) + size(framings) AS examined, violations,
       CASE WHEN size(selections) + size(framings) = 0 THEN 'FAIL: nothing checked'
            WHEN size(violations) > 0 THEN 'FAIL' ELSE 'PASS' END AS verdict

// Validator v6b-near-miss
// V6b near-miss (DESIGN §5.1, audit): every Selection has another Candidate of its use case within
// 20 points, so a reviewer sees a real alternative. Violations give WARN, not FAIL.
OPTIONAL MATCH (s:Selection {deal_code: $deal, iteration: $iteration})
WITH collect(s) AS selections
CALL (selections) {
  UNWIND selections AS s
  WITH s
  WHERE NOT EXISTS {
    MATCH (c:Candidate {deal_code: $deal, iteration: $iteration, uc: s.uc})
    WHERE c.pattern <> s.pattern AND abs(c.fit_score - s.fit_score) <= 20
  }
  WITH s ORDER BY s.uc
  RETURN collect({
    witness: [s.uc],
    witness_eids: [elementId(s)],
    detail: 'no alternative within 20 points of ' + s.pattern + ' for ' + s.uc
  }) AS violations
}
RETURN 'V6b' AS check, size(selections) AS examined, violations,
       CASE WHEN size(selections) = 0 THEN 'FAIL: nothing checked' WHEN size(violations) > 0 THEN 'WARN' ELSE 'PASS' END AS verdict

// Validator v7-edge-coverage
// V7 knowledge-edge coverage (DESIGN §5.1, data): the share of catalog patterns with any REQUIRES,
// CONFLICTS, or AUGMENTS edge is at least $floor. Global (no $deal). Violations list uncovered patterns;
// the verdict depends only on the share, which is also returned as coverage.
OPTIONAL MATCH (p:Pattern)
WITH collect(p) AS patterns
CALL (patterns) {
  UNWIND patterns AS p
  WITH p
  WHERE NOT EXISTS { (p)-[:REQUIRES|CONFLICTS|AUGMENTS]-(:Pattern) }
  WITH p ORDER BY p.id
  RETURN collect({witness: [p.id], witness_eids: [elementId(p)], detail: p.id + ' has no REQUIRES, CONFLICTS, or AUGMENTS edge'}) AS violations
}
WITH patterns, violations,
     CASE WHEN size(patterns) = 0 THEN 0.0 ELSE toFloat(size(patterns) - size(violations)) / size(patterns) END AS coverage
RETURN 'V7' AS check, size(patterns) AS examined, violations,
       CASE WHEN size(patterns) = 0 THEN 'FAIL: nothing checked' WHEN $floor IS NULL OR coverage < $floor THEN 'FAIL' ELSE 'PASS' END AS verdict,
       coverage
