import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ontology } from '@planner/ontology';

/**
 * Generates browser/style.grass and browser/favorites.cypher (T4.2 addendum §5.5) from the ontology and
 * the very queries the demo UI and the skill run. `npm run browser:gen`; a test keeps them in sync.
 */

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const read = (p: string) => readFileSync(join(ROOT, p), 'utf8').trim();

// Same palette as viz/src/style.ts; OntologyTerm's `meta` subgraph is shown as ontology.
const PALETTE: Record<string, string> = {
  knowledge: '#9DB8C7',
  evidence: '#FF9A7A',
  plan: '#8EE3EA',
  decisions: '#B79CFF',
  meta: '#F4C25A',
};

const CAPTION: Record<string, string> = {
  Pattern: 'name',
  Task: 'summary',
  UseCase: 'display',
  Track: 'name',
  CapabilityType: 'name',
  PlatformCapability: 'name',
  Deal: 'code',
  Selection: 'uc',
  Candidate: 'pattern',
  PlanTask: 'task_id',
  CapabilityDecision: 'capability_id',
  Override: 'kind',
  Finding: 'id',
  GateDecision: 'gate',
  OntologyTerm: 'name',
  Iteration: 'n',
  Roadmap: 'version',
};

export function grass(): string {
  const node = (label: string, color: string, caption: string) =>
    `node.${label} {\n  diameter: 50px;\n  color: ${color};\n  border-color: ${color};\n  text-color-internal: #002B43;\n  font-size: 14px;\n  caption: "{${caption}}";\n}\n`;
  return [
    '/* Generated by scripts/gen-browser.ts: the demo palette for Neo4j Browser (:style, then drop this file). */\n',
    'node {\n  diameter: 50px;\n  color: #9DB8C7;\n  border-color: #9DB8C7;\n  text-color-internal: #002B43;\n  font-size: 14px;\n}\n',
    'relationship {\n  color: #4F7388;\n  shaft-width: 2px;\n  font-size: 12px;\n  caption: "<type>";\n}\n',
    ...ontology.labels.map((l) => node(l.name, PALETTE[l.subgraph] ?? '#9DB8C7', CAPTION[l.name] ?? 'id')),
  ].join('\n');
}

export function favorites(): string {
  const fav = (title: string, query: string) => `// ${title}\n${query}\n`;
  const validators = ['v1-prerequisite-closure', 'v2-conflicting-selections', 'v3-task-cycle', 'v4-uncovered-critical-gap', 'v5-excluded-pattern', 'v6-audit-chain', 'v6b-near-miss', 'v7-edge-coverage'];
  return [
    '// Generated by scripts/gen-browser.ts. Set parameters first, e.g.:\n// :param deal => "nimbus"\n// :param iteration => 1\n// Turn OFF "Connect result nodes" in Browser settings for the scene queries.\n',
    fav('Scene 1: Knowledge (patterns in play, their tasks, related patterns)', read('packages/gate/src/ui/scenes/scene1-knowledge.cypher')),
    fav('Scene 2: Plan (the iteration, its plan nodes, findings, patterns)', read('packages/gate/src/ui/scenes/scene2-plan.cypher')),
    fav('Scene 3: Decisions (gates, feedback, overrides, ontology terms)', read('packages/gate/src/ui/scenes/scene3-decisions.cypher')),
    fav('Iteration diff (needs iteration >= 2)', read('graph/queries/skill/iteration_diff.cypher')),
    fav('Resource load by skill and wave (after scheduling)', read('graph/queries/resource-load.cypher')),
    fav('BB1 buy vs build', read('graph/queries/skill/bb1.cypher')),
    ...validators.map((v) => fav(`Validator ${v}`, read(`graph/queries/validators/${v}.cypher`))),
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(ROOT, 'browser/style.grass'), grass());
  writeFileSync(join(ROOT, 'browser/favorites.cypher'), favorites());
  console.log('browser: wrote style.grass and favorites.cypher');
}
